# Generated by Django 5.1.4 on 2025-01-16 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Destination',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('img', models.ImageField(upload_to='images')),
                ('desc', models.TextField()),
                ('adult_price', models.IntegerField()),
                ('child_price', models.IntegerField()),
                ('infant_price', models.IntegerField()),
            ],
        ),
    ]
