# Generated by Django 5.1.4 on 2025-01-10 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='createaccount',
            name='account',
            field=models.CharField(choices=[('Standard', '1'), ('Premium', '2'), ('VIP', '3')], max_length=200),
        ),
    ]
