# Generated by Django 5.1.4 on 2025-01-14 13:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_alter_createaccount_account'),
    ]

    operations = [
        migrations.AlterField(
            model_name='createaccount',
            name='account',
            field=models.CharField(choices=[('Standard', 'Standard'), ('Premium', 'Premium'), ('VIP', 'VIP')], default='Standard', max_length=200),
        ),
        migrations.CreateModel(
            name='Trips',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('item_des', models.CharField(max_length=100)),
                ('item_price', models.FloatField(max_length=100)),
                ('item_no', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
