# Generated by Django 5.1.4 on 2025-01-14 13:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_alter_createaccount_account_trips'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trips',
            name='item_no',
        ),
    ]
